### ISSUE TITLE
Why background colors are "!important"?

### ISSUE THREAD

**Issue by ffsantos92** [ConciseCSS/concise.css#185]
I believe that `!important` property should be avoided on `bg--mute`, `bg--primary`, `bg--success`, `bg--warning`, `bg--error` since it is not needed (e.g. for buttons).

**Comment by jameskolce** [comment]
Because they are utility classes, so we use `!important` to override any other styles. Most of the time is not necessary for the level of specificity, but sometimes it is. However, apart from being sometimes unnecessary, why do you think it should be avoided? So I can take it into consideration for the next version! Thanks.

**Comment by ffsantos92** [comment]
For example, there are no big visual differences if you set a background color (e.g. `bg--success` or `border--success`) to a disabled button.

**Comment by jameskolce** [comment]
There are cases where, for specificity reasons, you need to use `!important`. Especially in utility classes which have priority and are meant to be used as single-purpose classes. In the example you said, if I'm getting it right, you have to have `!important` to make it work: http://codepen.io/anon/pen/ZOeWWX Without the `!important` you won't see any change.
The only thing I can think of about avoiding `!important` is when you want to override some rules, but since this classes have only one rule, just deleting the class would be enough, I hope I'm explaining myself, let me know what you think!

**Comment by ffsantos92** [comment]
I understand and i also agree with you but a solution for disabled buttons could be changing the opacity. So, we can easily distinguish a disabled button form an enabled one.

Example: http://codepen.io/anon/pen/oLZxMr

**Comment by jameskolce** [comment]
Ah now I understand, so the issue is just with the disabled button right? If so then I'll make the opacity change for the next version, you are right on that point.

**Comment by ffsantos92** [comment]
Yes, i have experienced the issue with disabled buttons.

Thanks :smile:

**Comment by jameskolce** [comment]
Sure! If you find any other issues just let me know!
