### ISSUE TITLE
Reconsider use of custom pr units

### ISSUE THREAD

**Issue by mshick** [ConciseCSS/concise.css#194]
I hope you won't mind my opinion / constructive criticism, but I find the choice of using custom `pr` units to be a disappointing direction for these styles. I find the custom unit to be a bit obscure, and seemingly unnecessary (it also adds another dependency). 

You can accomplish the same goal via a base font size of `10px` on the html element, and can then use `rem`s like pixel values, e.g., 1.8rem = 18px. This has been a convention I've seen for awhile now. It doesn't preclude using different font sizes on all site content, via, say, `16px` or `1.6rem` being set on the body tag.

I've also noticed that the `pr` units tend to create values like, `10.5667rem` which can create slight clipping on the edges of image elements (raster) that need to be rounded to whole pixels.

**Comment by jameskolce** [comment]
Oh no, I appreciate criticism because it helps me too; if someone proves that I'm wrong, then I'll learn. Feel free to critique everything.

Now going to the point, the first thing you mention about using `10px` as root size makes sense to me, and is totally fine to use it, but I think you also get a little extra thing to keep in mind. Because `rem` is equivalent to the root `font-size` you also have to know how much is it, in this case `10px`, and that's totally fine for an individual project but might not be completely clear for a generic tool used in lots of projects. 
That's why I created this new unit where you don't have to think about the root font-size since it gets it automatically, and always is going to produce the pixel equivalent (or the closest possible).

The `pr` unit shouldn't be obscure, but I understand what you say because I haven't documented its use properly yet (actually there isn't even docs about this new Concise version), so here is the deal: when you use the `pr` unit you should think of it like "I want to use pixels, but I still want them to behave dynamically".

So it's basically the same idea you mention, but in this case you don't have to keep in mind that 1rem would be 10px. 
Also, with the `pr` unit it doesn't matter if someone (even accidentally) changes the root `font-size` since the unit will be transformed into the pixel equivalent anyway.

And lastly, about the images, it might not be specifically an issue with this but an issue with the design approach, this might be just unmasking the problem. I would have to look that in more detail and if you could provide a complete example it would be really helpful. I suspect it might be an issue with trying to get pixel-perfect designs (which is not the best thing to do, proportions are almost always better than precise measures).

I hope all this makes sense because I'm writing past midnight, but if there is still something unclear or if you don't agree, let me know and we can get somewhere.

**Comment by jameskolce** [comment]
So I'm going to close this issue now. If you still have any comments you can reopen it.

**Comment by mshick** [comment]
Ha, I think I typed a response and forgot to press send!

The gist of my saying it's obscure lies in the fact it's creating a static abstraction for "live" variables based on a single, original root font-size. 

That root font-size is commonly manipulated, mostly by media queries, so if you do that you're saying something like "the new size of my element is the original `pr` size divided by the original root font-size multiplied by my new root font-size" instead of "the new size is the element size multiplied by the current root font-size".

Anyway, just a comment, I appreciate the creativity, I just don't often see framework projects using custom units, especially given how many (already confusing) units CSS offers.

**Comment by jameskolce** [comment]
Oh I think I understand what you mean now, and I agree, but now we have a problem because I think both of our solutions have problems, so we (or I) will have to think of a third solution, or maybe we are just trying to do the wrong thing.
I was thinking about it and maybe the issue comes from something deeper, maybe from the principle of thinking in static units like in other areas of design; the web is an extremely dynamic environment so thinking in static units might not be a correct thing to do (unless for real precise things like borders) and as I mentioned in the other comment "proportions are almost always better than precise measures". In the framework, I use this unit for font sizes (if I use it in other places must be a mistake), especially for headings, but since I'm also generating those pixels values using a scale based on the base font-size, I think it might be doing things redundant.
So I'll reconsider the use of this unit indeed, and adjust some fundamentals in the framework like the generation of the type scale. Since it's based on proportions I could use rems directly.
Good catch, I appreciate it!

**Comment by mshick** [comment]
Just my opinion! Thanks for considering it, but really, do what makes the most sense to you.

I'm not sure that you did use `pr` anywhere other than fonts. I was just trying to be consistent in terms of units in the custom styles I wrote that built on concise.

**Comment by jameskolce** [comment]
Yeah, so I just started to work on this and got a better solution that won't require the use of the pr unit and won't require setting the root font-size to 10px neither, so I'm glad you pointed out this even if the proposed solution wasn't optimal. 
I'm dropping some design-oriented solutions here so might not be obvious at first for front-end developers but when the next version is released I'll make sure the docs are clear because now the recommended way to set font-sizes is going to be to pick a size from the provided type scale instead of writing pixels (or ems/rems) manually.

**Comment by jameskolce** [comment]
Done, now there are no "pr" units in the code and the font sizes are handled in the correct way (from a design perspective).

**Comment by mshick** [comment]
Nice!
