### ISSUE TITLE
Document requirement for postcss-media-minmax plugin

### ISSUE THREAD

**Issue by fizz** [ConciseCSS/concise.css#244]
Hi James, I love ConciseCSS! It should be better known!

Just dropping a note to let you know that my grids didn't work until I did `npm install postcss-media-minmax`. At first I wondered if I'd found a Safari bug in attribute selector support. Chrome had the same problem, so I kept digging. At length, I tracked it down to this section of my _settings.scss, when I realized no media query documentation ever mentioned ">=" or "<=" as valid operators in media feature expressions:
```css
@custom-media --extra-small (width <= 480px);
@custom-media --small (width >= 480px);
@custom-media --medium (width >= 768px);
@custom-media --large (width >= 960px);
@custom-media --extra-large (width >= 1100px);
@custom-media --only-small (480px < width <= 768px);
@custom-media --only-medium (768px < width <= 980px);
@custom-media --only-large (980px < width <= 1100px);
```

I manually edited the media feature expression definitions to say "min-width" and "max-width", and then I wondered if maybe you were using some plugin to acquire this sweet syntactic sugar.   I didn't find anything in dependencies or devDependencies in your package.json, but I *finally* stumbled upon postcss-media-minmax and tried installing it. Finally! Everything worked.

Please document this prerequisite (by cutting a release with a modified package.json reflecting `npm i --save-dev postcss-media-minmax`, or by documenting the prerequisite on the website/readme, or both). It might save someone else the two hours of time I wasted on trying to figure this out :-)

**Comment by jameskolce** [comment]
Hi @fizz, thank you for your words! And first of all, I’m so sorry to hear that you had trouble and spent two hours with this, I’ll make sure it works fine.

The logic operators for the media queries are syntactic sugar provided by `postcss-media-minmax` indeed, and it’s actually [included as a dependency](https://github.com/ConciseCSS/concise-cli/blob/master/package.json#L21) in the package.json of the [Concise CLI](https://github.com/ConciseCSS/concise-cli).

So could you explain your workflow, how are you compiling the source code? Because I haven’t had this issue in my projects yet so I don’t know if it is because I didn’t explain something in the docs or if it is an actual bug in the code.

Please let me know and I’ll check this out, thanks!

**Comment by fizz** [comment]
Hmm, that is strange! I'm running node 6.8.0, which itself is installed via https://github.com/tj/n.

I'm compiling with Concise CLI installed globally, but it didn't seem to bring the dependency in at compile time. concise.css is installed in the project's package.json/node_modules. 

When I installed postcss-media-minmax, it was also a global install.

**Comment by fizz** [comment]
Additional mystery note: postcss-custom-media seemed to work just fine without manual installation, unlike postcss-media-minmax.

When I have time tonight or tomorrow, I'll try to send you reproducible steps to replicate the issue.

**Comment by jameskolce** [comment]
Yeah, I was thinking it might be a problem with the NPM installation, maybe it didn’t download `postcss-media-minmax` when your installed the Concise CLI. 

You can try reinstalling the CLI, and deleting your global installation of `postcss-media-minmax` to be sure. If that works it means it was just a bad installation. Let me know!

**Comment by jameskolce** [comment]
@fizz Any news? I have been using Concise CSS a lot and I haven't had any problem, I'll close the issue for now but if you still have any problem feel free to open it again. Thanks.
