### ISSUE TITLE
Request: Core + Utils + UI = One repo

### ISSUE THREAD

**Issue by inseldesign** [ConciseCSS/concise.css#245]
Hey James,

before ConciseCSS was updated to version 4.0, all part where packed in one repo. As I can imagine that there is a plan behind to divide the parts into different repos, do you think that there is any chance to combine those parts again? 
In my case I often work with CodeKit and install/update packages via bower. The install/update process with ConciseCSS UTILS and UI (in case they are available via bower) will now be more difficult.

Thanks in advance and thanks for this powerful framework.

Sascha

**Comment by jameskolce** [comment]
Hey @inseldesign, thanks for using Concise!

I decided to split the code in different repositories depending on their type so I can work on them independently, without having to release new versions of the core for every change in an add-on for example. Also, the Core is the only essential part of the framework, so I wanted to emphasize that everything else is optional. By making them separate packages, we get only what we need.

Finally, it's more efficient to work on this when each component is clearly delimited, so I don't think that will change, at least not in the close future.

Although I won't merge the repositories again, I can create a new one just as a wrapper when people need to include the three things at the same time, I'll do it in this repo: https://github.com/jameskolce/concise-wrapper and probably will be available in NPM and Bower as `concise-wrapper` as well.

In the future I would move the wrapper in this repository and move the core to a new one, I think that would be ideal. But it would be a breaking change for v5 so it will take a while since I just released this version. For now, the previous idea could work, what do you think?

I still have to publish the add-ons in Bower, I'll do it in a few hours!

**Comment by jameskolce** [comment]
By the way, I haven't used CodeKit, but if you plan to build the Concise files with it, I think it won't work since we are not using pure Sass anymore. The only easy way so far is with the Concise CLI, unless. Unless you are using the precompiled CSS files, in which case is everything fine.

I do have plans to build an app to work with the framework at some point, though that will take some time.

**Comment by inseldesign** [comment]
Hey James,

thanks for your answer(s) and for creating the wrapper repo. Due to the fact that some PostCSS modules are used, Codekit compiles without giving an error message but "lh" is also inside the compiled css an so it won't work in browser.

Concise CLI will also work for me. But since I am design things, I have read through all this dev stuff with gulp (or other) to get things done via file-watching and auto-compiling... :-) but i will cope with that.

ConciseCSS for me (as a designer) is one of the most intuitive css frameworks. Thanks again for your (and your devs) outstanding work!

**Comment by jameskolce** [comment]
Thank you for your words; I'm happy to see that you find the framework useful!

But yeah, currently the Concise CLI is the only way to compile the files easily, so try to use it and if you find any problem or question you can open an issue and I'll help, in that way, I can improve the documentation too.

About the workflow, I would recommend my other project called Chaos: https://github.com/jameskolce/chaos where you can see my usual setup to build static websites with Concise CSS or use it directly as a starting point if you want.

Cheers!

**Comment by inseldesign** [comment]
Thank you. Got it working with the Concise CLI and Hook inside Codekit. :-)
