### ISSUE TITLE
typo in _getColor-function.scss

### ISSUE THREAD

**Issue by FredHall** [ConciseCSS/concise.css#257]
Based upon the colors specified in `globals/_settings.scss`, the following correction should be made to `globals/_getColor-function.scss`

```diff
--  @function getColor($color, $value: "base") {
++ @function getColor($color: "base", $value: "primary") {
  @return map-get(map-get($colors, $color), $value);
}
```

**Comment by jameskolce** [comment]
Is there any problem with the current function? I can't find any issue.

I think using `primary` would be better and also add a default value for `$color` but that would be a breaking change because I would have to change the name of the following colors, where `base` is used instead of `primary`.

```scss
red: (
    "darker":  #653131,
    "dark":    #b73333,
    "base":    #da3c3c,
    "light":   #f25a5a,
    "lighter": #fa8181
  ),
```

I think some improvements could be made here but perhaps for a next major version. So I'll leave this open for the future. But let me know if you think there is a mistake here!

**Comment by FredHall** [comment]
Your correct. I was looking at...

$colors: (
  base: (
    "primary":   #C65146,
    "selection": #EBE1D3,
    "lines":     #DCDCDC
  ),

Which is why I made the suggestion I did. I would close this out as invalid.

I think we could do better with standardizing the naming of colors, but these changes would break existing applications, so best wait as you recommended.
