### ISSUE TITLE
How can I remove these vertical scroll bars

### ISSUE THREAD

**Issue by xsmobi** [ConciseCSS/concise.css#268]
Hello,

I tested ConciseCSS here: http://www.xsmobi.com/cccss.html - works great, excellent results with Google mobile speed test http://i.imgur.com/tiJ6NGa.jpg

(Content is normal HTML + AJAX via Javascript in div "demo" - AJAX via jQuery in div "post" + a Slick slider via AJAX)

Problem: there is this ugly **vertical scroll bar**. It shows up when I wrap content in `<main container></main>`. If I omit the `<main>` tag, mobile friendlyness drops from 90%+ to around 70% (because the viewport does not fit anymore).

Can you help?

Best, Eckard

**Comment by jameskolce** [comment]
Hi @xsmobi

Add this to your CSS:

```scss
[container] {
  overflow: visible;
}
```

That's because the current version has `overflow: auto`, which I have to remove, but I'm not quite sure when I'll release a new version with the fix (at some point is going to happen though).

By the way, you have nested containers in your code, you shouldn't have a `container` inside another `container`.

I hope that helps!

**Comment by xsmobi** [comment]
Hi @jameskolce 
thank you, did both tweaks and it works nicely. Such a great framework! Going to be on the lookout for new example templates and the new version.

**Comment by jameskolce** [comment]
Awesome, thanks!
