### ISSUE TITLE
CDN is down

### ISSUE THREAD

**Issue by fregante** [ConciseCSS/concise.css#290]
This won't load https://cdn.concisecss.com/concise.min.css

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1402241/78513423-dda65580-77ab-11ea-9eff-11461ad7491e.png">

**Comment by Jaiheravi** [comment]
Yes, the CDN hasn't been working for a while (this project has been pretty much abandoned since 2017), but we just started working on a new version and I'll create a new CDN after that's done

**Comment by keenanpayne** [comment]
@fregante Sorry to hear that you're suffering from a CDN deprecation. I understand how much of a pain that is. 

Like @Jaiheravi said, this project has mostly been deprecated since 2017 as such, things like the CDN became deprecated as well. However, he and I are both working on a new version of Concise, and we will set up a new CDN so that Concise can be used in projects conveniently.

**Comment by keenanpayne** [comment]
@fregante Good news! @Jaiheravi and I got our CDN setup again so links to assets on cdn.concisecss.com should now be working correctly.

Please let me know if you run into any more issues 😃
