### ISSUE TITLE
Codepens fail in doc

### ISSUE THREAD

**Issue by raphaelgoetter** [ConciseCSS/concise.css#291]
Hello,

It seems that Codepen examples don't work properly in the doc (ex. https://concisecss.com/documentation/ui#alert-box )

Have a nice day!

**Comment by Jaiheravi** [comment]
Hey @raphaelgoetter Thanks for reporting this, seems like the cause is that the CDN is also down (https://github.com/ConciseCSS/concise.css/issues/290) and those examples use it.

This project has been unmaintained for a couple of years, but @keenanpayne and I are currently working on a new version, once we get that done soon we will set up a new CDN and a new website, including new examples. Have a nice day you too!

**Comment by keenanpayne** [comment]
@raphaelgoetter Thank you for reporting! @Jaiheravi and I have fixed #290 which also fixes this issue. All demos inside of the Concise documentation should be working correctly. 

Please let me know if you run into any more issues 😃
