### ISSUE TITLE
Is there an accordion component available for Concise?

### ISSUE THREAD

**Issue by bobrocke** [ConciseCSS/concise.css#62]
I would think this would be an add-in. Any plans?

**Comment by jameskolce** [comment]
Not officially. I don't know if there is any third-party accordion component that works with this framework though.
Currently we are working in deleting all the Javascript in the framework to make it as clean as possible, since this is a CSS framework, but unfortunately there is no way to make decent accordion components with only CSS. So I think you would need to search for a standalone solution.

**Comment by bobrocke** [comment]
Interesting, no JavaScript at all. Will that make responsive navigation, drop downs, and closable items impossible?

**Comment by jameskolce** [comment]
We can have those things with pure CSS but they won't behave as good as with JS.
Currently for the next version we have nice tooltips and fully functional modal windows with pure CSS. Dropdowns are in the process and we have plans to make responsive navigation modules too.

Maybe I could check again about making accordions, I'll let you know about that.

**Comment by jameskolce** [comment]
I was thinking and we might leave components like accordions out of the project to keep everything clean and simple. To fill the need of those components I could make them in JS, compatible with the framework but as a third-party solution. So when the next version is out check my profile for components like this!

**Comment by bobrocke** [comment]
That sounds like a plan. Concise stays simple and light; people who wish for more functionality can get components that are know to work smoothly with Concise. That would be much like the add-on are now, but from third parties working to match Concise's model.
