### ISSUE TITLE
Conditional styling beats text-align

### ISSUE THREAD

**Issue by stegrams** [ConciseCSS/concise.css#89]
I tested some ```hide--*``` on Narrow Templates 'Read More' button which was repositioned to the left as a result of it's ```display``` conversion from ```inline-block``` to ```block```.

The solution may be to change the mixin's ```show-conditional``` ```display``` value to ```initial``` but, as i see, that is not supported by everIE browser.

**Comment by jameskolce** [comment]
Hi @stegrams Sorry for the late reply.
We will check this out, thanks!

**Comment by jameskolce** [comment]
This is an interesting problem, since the CSS properties that would fix this aren't supported by all modern browsers. 
My recommendation is to avoid using those classes for non-block elements. I think it would be impractical to include a variation for each type of most common displays (`inline`, `inline-block`, `block`), instead I would do it directly for the element:

```SASS
.myBlockElement {
  display: none;
  visibility: hidden;
  // Show only on small devices
  @media (min-width: $bp-small) {
    display: block;
    visibility: visible;
  }
}

.myInlineBlockElement {
  display: none;
  visibility: hidden;
  // Show only on small devices
  @media (min-width: $bp-small) {
    display: inline-block;
    visibility: visible;
  }
}
```
But I'll keep this problem in mind for the future.
